### ISSUE TITLE
toolbox/api_lock.h: No such file or directory

### ISSUE THREAD

**Issue by LeJawa** [biotinker/flipperzero-gpioreader#1]
I have tried to compile the app but I get the following error:
`applications_user/flipperzero-gpioreader/usb_uart_bridge.c:6:10: fatal error: toolbox/api_lock.h: No such file or directory`

I am running on the container where I succesfully compile the entire official firmware.

I have run the command in the README: `./fbt launch_app APPSRC=flipperzero-gpioreader`

I couldn't find `api_lock.h` file in the repo. However `FuriApiLock`,  is added by `dialogs_api_lock.h`.
Changing line 6 to `#include "dialogs_api_lock.h"` didn't help compiling (although VS Code stopped complaining...)

Unfortunately I don't have time to look deeper into the issue tonight, I'll look again tomorrow.

**Comment by biotinker** [comment]
Hi,
Can you confirm your checkout of `flipperzero-firmware` is up to date?

The file in question is here: https://github.com/flipperdevices/flipperzero-firmware/blob/dev/lib/toolbox/api_lock.h

This file was only added to the upstream repo 3 days ago, so if you are building off an old checkout, this will not work.

**Comment by LeJawa** [comment]
**\*facepalm\***
Turns out I was running it on my local fork...

Now it compiles! Interestingly, the command still didn't fully work and told me that it couldn't find my flipper.
But it's probably because I am running the repo in a container. 

Didn't really investigate because compiling in the usual way (`./fbt fap_dist`) worked like a charm and I could then install the app manually on my flipper.

Thanks a lot for the help!
